const signUpUser = async () => {
  try {
  } catch (err) {
    console.log(err);
    return {
      success: false,
      message: err,
    };
  }
};

const signInUser = async () => {
  try {
  } catch (err) {
    console.log(err);
    return {
      success: false,
      message: err,
    };
  }
};

const getUserById = async () => {
  try {
  } catch (err) {
    console.log(err);
    return {
      success: false,
      message: err,
    };
  }
};

export const userService = {
  signUpUser,
  signInUser,
  getUserById,
};
